version: "3.9"

services:
  api:
    build: ./API
    user: root
    container_name: api
    tty: true
    stdin_open: true
    volumes: 
        - "./API:/app/API:z"
        - "./Database:/app/Database:z"
    ports:
        - "65000:65000"
        - "80:80"