version: "3.9"

services:
  api:
    build: ./API
    container_name: api
    tty: true
    stdin_open: true
    volumes: 
        - "./API:/app/api"
        - "./Database:/app/db"
    ports:
        - "65000:65000"
        - "80:80"